<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Jogadores\" />
    <Folder Include="Tokens\" />
    <Folder Include="Partida\" />
    <Folder Include="Projetos\" />
  </ItemGroup>

</Project>
