<Project Sdk="Microsoft.NET.Sdk.Web">


  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\CapitalSyndicate.Application\CapitalSyndicate.Application.csproj" />
    <ProjectReference Include="..\CapitalSyndicate.Domain\CapitalSyndicate.Domain.csproj" />
  </ItemGroup>

</Project>
